export const FETCH_COFFEE_REQUEST = "FETCH_COFFEE_REQUEST";
export const FETCH_COFFEE_SUCCESS = "FETCH_COFFEE_SUCCESS";
export const FETCH_COFFEE_FAILURE = "FETCH_COFFEE_FAILURE";
export const SET_SORT_ORDER = "SET_SORT_ORDER";
