export const FETCH_MATCHES_START = "FETCH_MATCHES_START";
export const FETCH_MATCHES_FAILURE = "FETCH_MATCHES_FAILURE";
export const FETCH_MATCHES_SUCCESS = "FETCH_MATCHES_SUCCESS";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const SET_FILTER = "SET_FILTER";
export const MARK_FAVORITE = "MARK_FAVORITE";
